# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-23 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('question_asked', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Type the questions that you want to ask', unique=True)),
                ('choice_A', models.CharField(help_text='choices for the questions this field is required', max_length=120)),
                ('is_choice_A_correct', models.BooleanField(verbose_name='mark if the choice A is correct')),
                ('choice_B', models.CharField(help_text='choices for the question this field is required', max_length=120)),
                ('is_choice_B_correct', models.BooleanField(verbose_name='mark if the choice B is correct')),
                ('choice_C', models.CharField(blank=True, help_text='choices for the question this field is not required', max_length=120, null=True)),
                ('is_choice_C_correct', models.BooleanField(verbose_name='mark if the choice C is correct')),
                ('choice_D', models.CharField(blank=True, help_text='choices for the question this field is not required', max_length=120, null=True)),
                ('is_choice_D_correct', models.BooleanField(verbose_name='mark if the choice D is correct')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('explanation', models.TextField(blank=True, help_text='Explanation to be shown after the question has been answered.', max_length=2000, null=True, verbose_name='Explanation')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='title of the quiz', max_length=50, unique=True)),
                ('ask_random_questions', models.BooleanField(help_text='mark if you want to ask random questions, question order will be shuffled')),
                ('no_of_questions_to_ask', models.IntegerField(default=10, help_text='select no of questions that you want to ask the exam')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('session_name', models.CharField(help_text='this field is used to avoid the user to re-attend the same exam', max_length=120, unique=True)),
                ('question', models.ManyToManyField(to='mcQuiz.Question')),
            ],
        ),
    ]
