# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-23 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcQuiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampaper',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='exampaper',
            name='exam_detail',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
