# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcQuiz', '0002_auto_20200623_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='no_of_questions_to_ask',
            field=models.PositiveIntegerField(default=10, help_text='select no of questions that you want to ask the exam'),
        ),
    ]
