# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-24 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcQuiz', '0003_auto_20200623_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='has_session',
            field=models.BooleanField(default=False),
        ),
    ]
