# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-24 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcQuiz', '0004_subject_has_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_C',
            field=models.CharField(default='hai', help_text='choices for the question this field is required', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_D',
            field=models.CharField(default='hai', help_text='choices for the question this field is required', max_length=120),
            preserve_default=False,
        ),
    ]
